name = "Newb Glow"
version = [0, 2, 6]
min_supported_mc_version = [1, 21, 20]
description = '''
ยงc%w
ยง7- An enchanced vanilla shader for Minecraft!
%v
ยง3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["ChizaXXVII", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "debe30f7-26c3-4522-bd6b-4df6e29810d4" # Use https://www.uuidgenerator.net/version4
materials = ["Actor", "RenderChunk"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "CUSTOM"
materials = []
description = '''
2 custom texture
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
1 Default
'''